# /XAgentServer/docker-compose.yml

version: '3'

services:
  XAgentServer:
    image: xagent-server:0.2
    build:
      context: ..
      dockerfile: ./XAgentServer/dockerfiles/Dockerfile
    networks:
      -  web-server-network
    container_name: XAgent-Server
    ports:
      - "5173:5173"
      - "8090:8090"


networks:
  web-server-network:
    driver: bridge
